import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TaskFlow | Kormokhetro",
  description: "Task Management System",
  manifest: "/manifest.webmanifest", // Points to the PWA manifest generated by app/manifest.ts
};

// This configures the mobile viewport to look like an app (no zooming, correct colors)
export const viewport: Viewport = {
  themeColor: "#000000", // Should match the background_color in your manifest
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // Prevents users from pinching to zoom, feeling more "native"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
